
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2-slim
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "${KUMA_PORT_HOST}:3001"
    volumes:
      - "kuma_data:/app/data"
    environment:
      - TZ=${TZ}

volumes:
  kuma_data:
