name: Deploy to FROG

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python and Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        env:
          FROG_SERVER: ${{ secrets.FROG_SERVER }}
          FROG_SSH_PORT: ${{ secrets.FROG_SSH_PORT }}
          FROG_LOGIN: ${{ secrets.FROG_LOGIN }}
          FROG_PASSWORD: ${{ secrets.FROG_PASSWORD }}
        run: |
          ansible-playbook -i ansible-inventory ansible-deploy.yml --ssh-extra-args='-o StrictHostKeyChecking=no'
